
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: guestbook-pr
  namespace: guestbook
  labels:
    app: guestbook-app
spec:
  clusterReplicas: 2
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - aws-cluster-shared-0
      - aws-cluster-shared-1	
      #- azure-rhacm-cluster-05
