
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: guestbook-pr
  namespace: guestbook
  labels:
    app: guestbook-app
spec:
  clusterReplicas: 2
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - brisbane-cluster
      - sydney-cluster
      - melbourne-cluster
#      - bm-cluster

