---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: guestbook
  name: redis-slave-app-placement-1
  labels:
    app: redis-slave-app
spec:
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - sydney-cluster
      - singapore-cluster
